package com.mycompany.attemp1;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tris1702
 */
public class Main extends javax.swing.JFrame implements ActionListener{
    boolean gameOver = false;
    static boolean start = true;
    public static Manage manage = new Manage();
//    PlayPanel playPanel = new PlayPanel();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        manage.confirm.setBounds(320, 200, 572, 536);
        manage.tutorial.setBounds(300, 100, 849, 221); 
        manage.playPanel.setBounds(0, 0, 1215, 937);
        manage.menu.setBounds(0, 0, 1215, 937);
        manage.about.setBounds(200, 50, 800 ,800);
        manage.playPanel.setVisible(false);
        manage.tutorial.setVisible(false);
        manage.menu.setVisible(false);
        manage.confirm.setVisible(true);
        manage.about.setVisible(false);        
        setSize(manage.playPanel.getSize());
        setLocationRelativeTo(null);
        add(manage.confirm);
        add(manage.playPanel);
        add(manage.tutorial);
        add(manage.menu);
        add(manage.about);
//        Menu menu = new Menu();
//        
//        while (true){
//            if (menu.getPlay() == true)
//            {
//                menu.dispose();
//                break;
//            }
//        }
//        MyFrame myFrame = new MyFrame();
//        while (true)
//        {
//            if (myFrame.getGameOver() == true)
//            {
//                myFrame.dispose();
//                break;
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent arg0) {
                System.out.println(manage.playPanel.getGameOver());
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
