/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.attemp1;

import static com.mycompany.attemp1.Main.manage;

/**
 *
 * @author tris1702
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tutorButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        aboutButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        playButton.setBackground(new java.awt.Color(130, 152, 174));
        playButton.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                playButtonComponentRemoved(evt);
            }
        });
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 36)); // NOI18N
        jLabel2.setText("PLAY");

        javax.swing.GroupLayout playButtonLayout = new javax.swing.GroupLayout(playButton);
        playButton.setLayout(playButtonLayout);
        playButtonLayout.setHorizontalGroup(
            playButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(playButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(playButtonLayout.createSequentialGroup()
                    .addGap(0, 83, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 83, Short.MAX_VALUE)))
        );
        playButtonLayout.setVerticalGroup(
            playButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
            .addGroup(playButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(playButtonLayout.createSequentialGroup()
                    .addGap(0, 50, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 50, Short.MAX_VALUE)))
        );

        tutorButton.setBackground(new java.awt.Color(137, 162, 188));
        tutorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tutorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tutorButtonMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 1, 36)); // NOI18N
        jLabel3.setText("TUTORIAL");

        javax.swing.GroupLayout tutorButtonLayout = new javax.swing.GroupLayout(tutorButton);
        tutorButton.setLayout(tutorButtonLayout);
        tutorButtonLayout.setHorizontalGroup(
            tutorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(tutorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tutorButtonLayout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 41, Short.MAX_VALUE)))
        );
        tutorButtonLayout.setVerticalGroup(
            tutorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
            .addGroup(tutorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tutorButtonLayout.createSequentialGroup()
                    .addGap(0, 50, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 50, Short.MAX_VALUE)))
        );

        aboutButton.setBackground(new java.awt.Color(123, 163, 203));
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutButtonMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu Light", 1, 36)); // NOI18N
        jLabel4.setText("ABOUT");

        javax.swing.GroupLayout aboutButtonLayout = new javax.swing.GroupLayout(aboutButton);
        aboutButton.setLayout(aboutButtonLayout);
        aboutButtonLayout.setHorizontalGroup(
            aboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
            .addGroup(aboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutButtonLayout.createSequentialGroup()
                    .addGap(0, 66, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 66, Short.MAX_VALUE)))
        );
        aboutButtonLayout.setVerticalGroup(
            aboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(aboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutButtonLayout.createSequentialGroup()
                    .addGap(0, 46, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 47, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 200)); // NOI18N
        jLabel1.setText("!KcuiQ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tutorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(469, 469, 469))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tutorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        Main.manage.menu.setVisible(false);
        Main.manage.playPanel.renew();
        Main.manage.playPanel.setVisible(true);
    }//GEN-LAST:event_playButtonMouseClicked

    private void playButtonComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_playButtonComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_playButtonComponentRemoved

    private void tutorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorButtonMouseClicked
        
    }//GEN-LAST:event_tutorButtonMouseClicked

    private void tutorButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorButtonMouseEntered
        Main.manage.menu.setVisible(false);
        Main.manage.tutorial.setVisible(true);
    }//GEN-LAST:event_tutorButtonMouseEntered

    private void tutorButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorButtonMouseExited
        Main.manage.menu.setVisible(true);
        Main.manage.tutorial.setVisible(false);
    }//GEN-LAST:event_tutorButtonMouseExited

    private void aboutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseEntered
        Main.manage.menu.setVisible(false);
        Main.manage.about.setVisible(true);
    }//GEN-LAST:event_aboutButtonMouseEntered

    private void aboutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseExited
        Main.manage.menu.setVisible(true);
        Main.manage.about.setVisible(false);
    }//GEN-LAST:event_aboutButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel playButton;
    private javax.swing.JPanel tutorButton;
    // End of variables declaration//GEN-END:variables
}
